version: '3.8'
services:
  backend:
    build: .
    container_name: sandvik-lh410-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
  mongo:
    image: mongo:6
    container_name: sandvik-lh410-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: 